#PBS -l select=40:ncpus=48:mpiprocs=12
#PBS -l walltime=999:00:00
#PBS -j oe  
#PBS -N sed-idx-pos
#PBS -V 

echo "Starting job..."
module load intel
module list 

echo "Configuring workspace..."
export CPATH=/home/users/vitorss/simulation/sedimentation/exp-idx-pos
export DATAPATH=$CPATH/data
export DATAFLOW_TAG=sedimentation
export DFA=/home/users/vitorss/simulation/sedimentation/dfa
cd $CPATH

echo "Configuration properties to the sedimentation solver..."
TMAX=25.000
DELTAT=0.005
WRITE_INTERVAL=50
IMAGES=`echo $TMAX $DELTAT $WRITE_INTERVAL | awk '{print int(($1/$2)/$3)}'`

#echo "Specifying dataflow generation..."
#./pg-dataflow.sh

echo "Configuring the lists of machines for the solver and database system..."
cp $PBS_NODEFILE nodes.txt
java -jar /home/users/vitorss/simulation/sedimentation/bin/EnvironmentFileGenerator-LoboC-1.0.jar nodes.txt

echo "Starting database system..."
rm -rf data
unzip /home/users/vitorss/local/all/monetdb/monetdb-database.zip
/home/users/vitorss/simulation/sedimentation/bin/database_starter.sh database.conf $CPATH $DATAPATH
sleep 15

echo "Setting up environment variables..."
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user2/local/gnu/paraview/5.1/lib/paraview-5.1
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/users/vitorss/local/all/paraview/lib/paraview-5.1
export PYTHONPATH=/home/users/vitorss/local/all/paraview-5.2.0/lib/paraview-5.2/site-packages:/home/users/vitorss/local/all/paraview-5.2.0/lib/paraview-5.2
export LD_LIBRARY_PATH=/home/users/vitorss/local/all/paraview-5.2.0/lib/paraview-5.2:$LD_LIBRARY_PATH

echo "Executing sedimentation solver..."
/usr/bin/time mpirun /home/users/vitorss/simulation/sedimentation/libmesh-sedimentation/libmesh-sedimentation-opt -i sedimentation.in -m necker3d.msh -e extraction.py -v visualization.py -o output -d $CPATH/output/ >> out.txt 2>> err.txt

echo "Calculating total elapsed times based on log files..."
java -jar /home/users/vitorss/simulation/sedimentation/dfa/ProvenanceAnalysis.jar $CPATH/prov $IMAGES >> out.txt 2>> err.txt

#echo "Executing termination algorithm..."
#/home/users/vitorss/simulation/sedimentation/bin/termination.sh $CPATH $DATAFLOW_TAG
#/home/users/vitorss/simulation/sedimentation/bin/database_stopper.sh database.conf $CPATH $DATAPATH

echo "Finishing job..."






