#PBS -l select=41:ncpus=48:mpiprocs=12
#PBS -l walltime=999:00:00
#PBS -j oe  
#PBS -N sed-idx-ofb
#PBS -V 
JCORES=480

echo "Starting job..."
module load intel
module list 

echo "Configuring workspace..."
export CPATH=/scratch/10061a/vitorss/simulation/sedimentation/exp-idx-ofb
export DATAPATH=$CPATH/data
export DATAFLOW_TAG=sedimentation
export DFA=/scratch/10061a/vitorss/simulation/sedimentation/dfa
cd $CPATH

echo "Configuration properties to the sedimentation solver..."
TMAX=15.000
DELTAT=0.005
WRITE_INTERVAL=1
IMAGES=`echo $TMAX $DELTAT $WRITE_INTERVAL | awk '{print int(($1/$2)/$3)}'`

#echo "Specifying dataflow generation..."
#./pg-dataflow.sh

echo "Configuring the lists of machines for the solver and database system..."
cp $PBS_NODEFILE nodes.txt
java -jar /scratch/10061a/vitorss/simulation/sedimentation/bin/EnvironmentFileGenerator-LoboC-1.0.jar nodes.txt

echo "Starting database system..."
rm -rf data
unzip /home/users/vitorss/local/all/monetdb/monetdb-database.zip
/scratch/10061a/vitorss/simulation/sedimentation/bin/database_starter.sh database.conf $CPATH $DATAPATH
sleep 15

echo "Setting up environment variables..."
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user2/local/gnu/paraview/5.1/lib/paraview-5.1
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/users/vitorss/local/all/paraview/lib/paraview-5.1
export PYTHONPATH=/home/users/vitorss/local/all/paraview-5.2.0/lib/paraview-5.2/site-packages:/home/users/vitorss/local/all/paraview-5.2.0/lib/paraview-5.2
export LD_LIBRARY_PATH=/home/users/vitorss/local/all/paraview-5.2.0/lib/paraview-5.2:$LD_LIBRARY_PATH

echo "Executing sedimentation solver..."
#/usr/bin/time mpirun /scratch/10061a/vitorss/simulation/sedimentation/libmesh-sedimentation/libmesh-sedimentation-opt -i sedimentation.in -m necker3d.msh -e extraction.py -v visualization.py -o output -d $CPATH/output/ >> out.txt 2>> err.txt

echo -n "/usr/bin/time mpirun -machinefile machines.conf -n $JCORES /scratch/10061a/vitorss/simulation/sedimentation/libmesh-sedimentation/libmesh-sedimentation-opt -i sedimentation.in -m necker3d.msh -e extraction.py -v visualization.py -o output -d $CPATH/output/ >> out.txt 2>> err.txt" > mpirun.sh 
chmod 774 mpirun.sh
./mpirun.sh

echo "Calculating total elapsed times based on log files..."
java -jar /scratch/10061a/vitorss/simulation/sedimentation/dfa/ProvenanceAnalysis.jar $CPATH/prov $IMAGES >> out.txt 2>> err.txt

echo "Executing termination algorithm..."
/scratch/10061a/vitorss/simulation/sedimentation/bin/termination.sh $CPATH $DATAFLOW_TAG
/scratch/10061a/vitorss/simulation/sedimentation/bin/database_stopper.sh database.conf $CPATH $DATAPATH

echo "Finishing job..."






